name: nurse_diary
description: Digital Companion targeted to nurses.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.3
  logger: ^1.2.2
  flutter_simple_dependency_injection: ^2.0.0
  http: ^0.13.3
  shared_preferences: ^2.0.6
  equatable: ^2.0.5
  intl: ^0.17.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.6
  bloc_test: ^9.1.4
  flutter_lints: ^2.0.0
  mocktail: ^1.0.1
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

